### ISSUE TITLE
运行代码时文件缺失

### ISSUE THREAD

**Issue by nlnkjb** [weiguangzhao/DF_MVR#3]
您好，我在运行时显示好像少了一个数据集的预处理文件Traceback (most recent call last):
  File "/home/zhangao/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/zhangao/DF_MVR-main/train.py", line 238, in Distributed_training
    dataset = Dataset(cfg)
  File "/home/zhangao/DF_MVR-main/dataset/pixel_face/dataset_preprocess.py", line 408, in __init__
    create_shared_memory(self.train_file_list)
  File "/home/zhangao/DF_MVR-main/dataset/pixel_face/dataset_preprocess.py", line 77, in create_shared_memory
    img_norm = np.load("dataset/pixel_face/npy/{}_img_norm.npy".format(fn)).copy()
  File "/home/zhangao/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/numpy/lib/npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/pixel_face/npy/00194010_img_norm.npy'
您看是我哪地方弄错了吗

**Comment by weiguangzhao** [comment]
Thanks for your attention. You need to Uncomment the L398,L399,L400 in the dataset_preprocess.py to save these npy files for the first running.

**Comment by nlnkjb** [comment]
十分抱歉再次打扰您，请问一下下面这个问题是因为我还没吧pixed_face数据集放到那个文件中还是代码中哪一块的我没注意到啊
Traceback (most recent call last):
  File "/home/zhangao/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/zhangao/DF_MVR-main/train.py", line 239, in Distributed_training
    dataset = Dataset(cfg)
  File "/home/zhangao/DF_MVR-main/dataset/pixel_face/dataset_preprocess.py", line 399, in __init__
    create_npy(self.train_file_list, self.mask_model)
  File "/home/zhangao/DF_MVR-main/dataset/pixel_face/dataset_preprocess.py", line 114, in create_npy
    img_norm, img_raw, kp_img_gt, face_mask, weight_map = Data_preprocess(list_name, mask_model)
  File "/home/zhangao/DF_MVR-main/dataset/pixel_face/dataset_preprocess.py", line 297, in Data_preprocess
    img_src, lm = load_img_and_lm(img_path, detector)  # detect
  File "/home/zhangao/DF_MVR-main/dataset/pixel_face/dataset_preprocess.py", line 144, in load_img_and_lm
    image = Image.open(img_path)
  File "/home/zhangao/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/PIL/Image.py", line 3227, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'dataset/pixel_face/train/00194/01/Images/0/t.jpg'

**Comment by weiguangzhao** [comment]
Yes, you should put the pixel-face dataset under the "./dataset/" directory.

**Comment by nlnkjb** [comment]
您好，我按照要求申请了pixel_face数据集，但是貌似没有回复，您知道还有途径获取吗？或者能否使用其他数据集进行训练

**Comment by weiguangzhao** [comment]
Hi, you can try to contact the first author of the pixelface paper directly. Multi-PIE is the alternative dataset.
